### ISSUE TITLE
执行ppx.exe报错

### ISSUE THREAD

**Issue by runc** [pangao1990/vue-pywebview-pyinstaller#14]
Traceback (most recent call last):
  File "main.py", line 99, in <module>
  File "main.py", line 62, in WebViewApp
  File "proxy_tools\__init__.py", line 132, in <lambda>
  File "proxy_tools\__init__.py", line 62, in _get_current_object
  File "webview\__init__.py", line 232, in screens
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\platforms\winforms.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

以上是错误堆栈，开发模式，没问题，但预打包，或者正式打包侯，执行exe就报上面的错误了。

**Comment by pangao1990** [comment]
你好，请问是不是使用了中文路径呢？我曾经有一次放在中文路径下就报错 cannot call null pointer pointer from cdata 'int(*)(void *, int)'。改成纯英文路径就好了。
