### ISSUE TITLE
用命令pnpm run start 的时候报错了，显示运行时异常

### ISSUE THREAD

**Issue by 15259291016** [pangao1990/vue-pywebview-pyinstaller#18]
Traceback (most recent call last):
  File ".\pyapp\main.py", line 99, in <module>
    WebViewApp()
  File ".\pyapp\main.py", line 95, in WebViewApp
    webview.start()  # 启动窗口
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
  File "D:\demo\RTU配置工具\pyenv\pyenv\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

**Comment by pangao1990** [comment]
你好，使用中文路径就会提示这个错误，改成英文路径就好了。 

https://github.com/pangao1990/PPX/issues/14
https://github.com/pangao1990/PPX/issues/17

**Comment by 15259291016** [comment]
> 你好，使用中文路径就会提示这个错误，改成英文路径就好了。
> 
> #14 #17

谢谢 谢谢  可以了
