### ISSUE TITLE
webview.util.WebViewException: You must have pythonnet installed in order to use pywebview.

### ISSUE THREAD

**Issue by 15259291016** [pangao1990/vue-pywebview-pyinstaller#24]
[pywebview] pythonnet cannot be loaded
Traceback (most recent call last):
  File "C:\Users\YFB-SERVER\AppData\Local\Programs\Python\Python37\lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\YFB-SERVER\AppData\Local\Programs\Python\Python37\lib\site-packages\webview\platforms\winforms.py", line 104, in <module>
    from . import cef as CEF
  File "C:\Users\YFB-SERVER\AppData\Local\Programs\Python\Python37\lib\site-packages\webview\platforms\cef.py", line 11, in <module>
    from cefpython3 import cefpython as cef
ModuleNotFoundError: No module named 'cefpython3'
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/PyCharm 2022.2.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\RTU配置工具\pyapp\mainCEF.py", line 98, in <module>
    WebViewApp()
  File "D:\RTU配置工具\pyapp\mainCEF.py", line 94, in WebViewApp
    webview.start(gui='cef')  # 启动窗口
  File "C:\Users\YFB-SERVER\AppData\Local\Programs\Python\Python37\lib\site-packages\webview\__init__.py", line 132, in start
    guilib = initialize(gui)
  File "C:\Users\YFB-SERVER\AppData\Local\Programs\Python\Python37\lib\site-packages\webview\guilib.py", line 102, in initialize
    raise WebViewException('You must have pythonnet installed in order to use pywebview.')
webview.util.WebViewException: You must have pythonnet installed in order to use pywebview.

**Comment by 15259291016** [comment]
使用兼容模式启动会报错

**Comment by 15259291016** [comment]
![image](https://github.com/pangao1990/PPX/assets/87016091/a5d41de8-e566-4d86-a97b-cf1e8638050d)

**Comment by 15259291016** [comment]
依赖我也安装了，但是启动还是报错，必须安装pythonnet才能运行pywebview

**Comment by pangao1990** [comment]
@15259291016 你好，请问在使用cef兼容模式之前，有没有进行初始化cef兼容模式操作呢？
`pnpm run init:cef`

**Comment by 15259291016** [comment]
没有

**Comment by 15259291016** [comment]
我试一下

**Comment by pangao1990** [comment]
我看你使用的环境是pyenv
![image](https://github.com/pangao1990/PPX/assets/36030293/e78fa98b-2836-4aff-9a88-d3b735d39113)

但其实，cef兼容模式使用的是 `pyenvCEF` 环境，在 `pnpm run init:cef` 初始化的时候，程序会创建`pyenvCEF` 环境。

**Comment by 15259291016** [comment]
我试一下
