### ISSUE TITLE
build后打开报错：ImportError: DLL load failed while importing _ssl: 找不到指定的模块。

### ISSUE THREAD

**Issue by WnagoiYy** [pangao1990/vue-pywebview-pyinstaller#41]
如题，大佬遇到过这个问题吗？

![image](https://github.com/pangao1990/PPX/assets/16523520/23450bcf-8827-4690-8dff-4dd0da7db077)

Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\__init__.py", line 25, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\http.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ssl.py", line 100, in <module>
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。

**Comment by WnagoiYy** [comment]
搞定了，应该是不能用conda相关的环境，重装一个py又好了 - -！

ImportError: DLL load failed while importing _ssl: 找不到指定的模块。 · Issue #7510 · pyinstaller/pyinstaller --- ImportError: DLL load failed while importing _ssl: 找不到指定的模块。 · Issue #7510 · pyinstaller/pyinstaller
https://github.com/pyinstaller/pyinstaller/issues/7510
